PLUGIN_ID = "saleor.plugins.securities"

# Securities management constants
DEFAULT_SECURITIES_BUFFER = 5  # Default safety securities buffer
DEFAULT_REORDER_POINT = 10  # Default reorder point
DEFAULT_REORDER_QUANTITY = 50  # Default reorder quantity

# Securities levels
SECURITIES_LEVEL_CRITICAL = "critical"
SECURITIES_LEVEL_LOW = "low"
SECURITIES_LEVEL_NORMAL = "normal"
SECURITIES_LEVEL_HIGH = "high"

SECURITIES_LEVELS = [
    SECURITIES_LEVEL_CRITICAL,
    SECURITIES_LEVEL_LOW,
    SECURITIES_LEVEL_NORMAL,
    SECURITIES_LEVEL_HIGH,
]

# Securities movement types
SECURITIES_MOVEMENT_ADJUSTMENT = "adjustment"
SECURITIES_MOVEMENT_PURCHASE = "purchase"
SECURITIES_MOVEMENT_SALE = "sale"
SECURITIES_MOVEMENT_RETURN = "return"
SECURITIES_MOVEMENT_TRANSFER = "transfer"
SECURITIES_MOVEMENT_DAMAGED = "damaged"
SECURITIES_MOVEMENT_EXPIRED = "expired"

SECURITIES_MOVEMENT_TYPES = [
    SECURITIES_MOVEMENT_ADJUSTMENT,
    SECURITIES_MOVEMENT_PURCHASE,
    SECURITIES_MOVEMENT_SALE,
    SECURITIES_MOVEMENT_RETURN,
    SECURITIES_MOVEMENT_TRANSFER,
    SECURITIES_MOVEMENT_DAMAGED,
    SECURITIES_MOVEMENT_EXPIRED,
]

# Notification types
NOTIFICATION_LOW_SECURITIES = "low_securities"
NOTIFICATION_OUT_OF_SECURITIES = "out_of_securities"
NOTIFICATION_REORDER_POINT = "reorder_point"
NOTIFICATION_OVERSTOCKED = "overstocked"

NOTIFICATION_TYPES = [
    NOTIFICATION_LOW_SECURITIES,
    NOTIFICATION_OUT_OF_SECURITIES,
    NOTIFICATION_REORDER_POINT,
    NOTIFICATION_OVERSTOCKED,
]