# Generated by Django 5.2.1 on 2025-07-18 00:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('securities', '0001_initial'),
        ('warehouse', '0035_alter_warehouse_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritiesSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.IntegerField(help_text='Quantity threshold to trigger reorder', validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_quantity', models.IntegerField(help_text='Quantity to order when reorder point is reached', validators=[django.core.validators.MinValueValidator(1)])),
                ('safety_stock', models.IntegerField(default=0, help_text='Safety securities buffer quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('max_stock_level', models.IntegerField(blank=True, help_text='Maximum securities level before overstock alert', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('lead_time_days', models.IntegerField(default=7, help_text='Lead time for restocking in days', validators=[django.core.validators.MinValueValidator(0)])),
                ('enable_auto_reorder', models.BooleanField(default=False, help_text='Enable automatic reorder suggestions')),
                ('track_expiry', models.BooleanField(default=False, help_text='Track expiry dates for this securities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='securities_settings', to='warehouse.stock')),
            ],
            options={
                'db_table': 'securities_settings',
            },
        ),
        migrations.CreateModel(
            name='Tickers',
            fields=[
                ('ticker', models.CharField(help_text='Ticker symbol (e.g., AAPL, SPY)', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Company/fund name', max_length=255)),
                ('type', models.CharField(choices=[('cs', 'Common Stock'), ('etp', 'Exchange Traded Product')], help_text="Type of security - 'cs' for stock, 'etp' for ETF", max_length=10)),
                ('exchange', models.CharField(help_text='Exchange where the ticker is traded', max_length=10)),
                ('active', models.BooleanField(default=True, help_text='Whether the ticker is actively traded')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Tickers',
                'db_table': 'tickers',
                'ordering': ['ticker'],
                'indexes': [models.Index(fields=['ticker', 'name'], name='idx_ticker_search'), models.Index(fields=['type'], name='tickers_type_7068e0_idx'), models.Index(fields=['exchange'], name='tickers_exchang_93fd19_idx'), models.Index(fields=['active'], name='tickers_active_2e198a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReorderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('reason', models.TextField()),
                ('urgency_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_reorder_suggestions', to='warehouse.stock')),
            ],
            options={
                'db_table': 'securities_reorder_suggestion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', 'is_processed'], name='securities__stock_i_2b33f2_idx'), models.Index(fields=['urgency_level', 'created_at'], name='securities__urgency_08339f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecuritiesAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('low_securities', 'Low Securities'), ('out_of_securities', 'Out Of Securities'), ('reorder_point', 'Reorder Point'), ('overstocked', 'Overstocked')], max_length=20)),
                ('message', models.TextField()),
                ('quantity_at_alert', models.IntegerField()),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_alerts', to='warehouse.stock')),
            ],
            options={
                'db_table': 'securities_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stock', 'alert_type'], name='securities__stock_i_227e60_idx'), models.Index(fields=['is_resolved', 'created_at'], name='securities__is_reso_50e016_idx')],
            },
        ),
        migrations.CreateModel(
            name='SecuritiesBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('supplier_reference', models.CharField(blank=True, max_length=255)),
                ('is_expired', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_batches', to='warehouse.stock')),
            ],
            options={
                'db_table': 'securities_batch',
                'ordering': ['expiry_date', 'received_date'],
                'indexes': [models.Index(fields=['stock', 'expiry_date'], name='securities__stock_i_647f87_idx'), models.Index(fields=['expiry_date', 'is_expired'], name='securities__expiry__012700_idx')],
                'unique_together': {('stock', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='SecuritiesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_demand', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('confidence_level', models.DecimalField(decimal_places=2, help_text='Confidence level as percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_demand', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('forecast_method', models.CharField(default='moving_average', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_forecasts', to='warehouse.stock')),
            ],
            options={
                'db_table': 'securities_forecast',
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['stock', 'forecast_date'], name='securities__stock_i_900e82_idx'), models.Index(fields=['forecast_date'], name='securities__forecas_17f2a1_idx')],
                'unique_together': {('stock', 'forecast_date', 'forecast_method')},
            },
        ),
        migrations.CreateModel(
            name='SecuritiesMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Positive for increase, negative for decrease')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('adjustment', 'Adjustment'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('transfer', 'Transfer'), ('damaged', 'Damaged'), ('expired', 'Expired')], default='adjustment', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('reference_order', models.CharField(blank=True, max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='securities_movements', to='warehouse.stock')),
            ],
            options={
                'db_table': 'securities_movement',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['stock', 'timestamp'], name='securities__stock_i_f840d3_idx'), models.Index(fields=['movement_type', 'timestamp'], name='securities__movemen_040f24_idx')],
            },
        ),
    ]
