# Generated by Django 4.2.16 on 2024-07-03 23:00

from decimal import Decimal
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradex', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.CharField(help_text='Unique identifier for the holding', max_length=100, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(help_text='Amount or quantity of the holding (non-negative integer)')),
                ('purchase_price', models.DecimalField(decimal_places=6, help_text='Purchase price per unit (non-negative)', max_digits=15, validators=[MinValueValidator(Decimal('0'))])),
                ('purchase_time', models.DateTimeField(help_text='Date and time when the holding was purchased')),
                ('market', models.CharField(help_text='Market or exchange where the holding was purchased', max_length=100)),
                ('currency', models.CharField(help_text='Currency code (ISO 4217 format, e.g., USD, EUR)', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portfolio Holding',
                'verbose_name_plural': 'Portfolio Holdings',
                'db_table': 'tradex_holding',
                'ordering': ['-purchase_time', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['purchase_time'], name='tradex_holding_purchase_time_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['market'], name='tradex_holding_market_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['amount'], name='tradex_holding_amount_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['currency'], name='tradex_holding_currency_idx'),
        ),
    ]