# Generated by Django 5.2.1 on 2025-07-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradex', '0002_holding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holding',
            new_name='tradex_hold_purchas_dfa41d_idx',
            old_name='tradex_holding_purchase_time_idx',
        ),
        migrations.RenameIndex(
            model_name='holding',
            new_name='tradex_hold_market_b22d00_idx',
            old_name='tradex_holding_market_idx',
        ),
        migrations.RenameIndex(
            model_name='holding',
            new_name='tradex_hold_amount_4578bd_idx',
            old_name='tradex_holding_amount_idx',
        ),
        migrations.RenameIndex(
            model_name='holding',
            new_name='tradex_hold_currenc_d09120_idx',
            old_name='tradex_holding_currency_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='tradex_oper_equity__dcac5d_idx',
            old_name='tradex_oper_equity__6e0a7a_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='tradex_oper_date_ti_13de24_idx',
            old_name='tradex_oper_date_ti_2fa0d0_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='tradex_oper_operati_68140a_idx',
            old_name='tradex_oper_operati_de3c98_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='tradex_oper_status_87d217_idx',
            old_name='tradex_oper_status_8a5e1d_idx',
        ),
        migrations.RenameIndex(
            model_name='operation',
            new_name='tradex_oper_market_94a678_idx',
            old_name='tradex_oper_market_7c8e2a_idx',
        ),
        migrations.AlterField(
            model_name='operation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
