# Generated by Django 5.2.1 on 2025-07-19 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_repopulate_user_number_of_orders'),
        ('product', '0200_merge_20250527_1210'),
        ('tradex', '0003_rename_tradex_holding_purchase_time_idx_tradex_hold_purchas_dfa41d_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUserAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Product Created'), ('updated', 'Product Updated'), ('deleted', 'Product Deleted'), ('variant_created', 'Product Variant Created'), ('variant_updated', 'Product Variant Updated'), ('variant_deleted', 'Product Variant Deleted'), ('media_created', 'Product Media Created'), ('media_updated', 'Product Media Updated'), ('media_deleted', 'Product Media Deleted')], default='created', help_text='Type of action performed on the product', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Additional context about the action (e.g., variant ID, changes made)')),
                ('source', models.CharField(blank=True, help_text="Source of the action (e.g., 'graphql_api', 'admin_panel', 'plugin')", max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who performed the action', null=True)),
                ('product', models.ForeignKey(help_text='Reference to the Saleor product', on_delete=django.db.models.deletion.CASCADE, related_name='tradex_user_associations', to='product.product')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tradex_product_associations', to='account.user')),
            ],
            options={
                'verbose_name': 'Product User Association',
                'verbose_name_plural': 'Product User Associations',
                'db_table': 'tradex_product_user_association',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product', 'action_type'], name='tradex_prod_product_b59a9d_idx'), models.Index(fields=['user', 'action_type'], name='tradex_prod_user_id_ab5e28_idx'), models.Index(fields=['timestamp'], name='tradex_prod_timesta_04690c_idx'), models.Index(fields=['action_type', 'timestamp'], name='tradex_prod_action__e30ca5_idx')],
            },
        ),
    ]
